spring:
  data:
    mongodb:
      username: revanth
      password: revanth
      host: localhost
      port: 27017
      database: customer
      authentication-database: admin
server:
  port: 8090
